name 'motd_cr'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motd_cr'
long_description 'Installs/Configures motd_cr'
version '0.1.0'
depends 'compat_resource', '~> 12.7.1'
